// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package person

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 *Person_Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                []*Person_Email `protobuf:"bytes,2,rep,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() *Person_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetEmail() []*Person_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type Person_Name struct {
	LastN                string   `protobuf:"bytes,1,opt,name=lastN,proto3" json:"lastN,omitempty"`
	GivenN               string   `protobuf:"bytes,2,opt,name=givenN,proto3" json:"givenN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person_Name) Reset()         { *m = Person_Name{} }
func (m *Person_Name) String() string { return proto.CompactTextString(m) }
func (*Person_Name) ProtoMessage()    {}
func (*Person_Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

func (m *Person_Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Name.Unmarshal(m, b)
}
func (m *Person_Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Name.Marshal(b, m, deterministic)
}
func (m *Person_Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Name.Merge(m, src)
}
func (m *Person_Name) XXX_Size() int {
	return xxx_messageInfo_Person_Name.Size(m)
}
func (m *Person_Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Name proto.InternalMessageInfo

func (m *Person_Name) GetLastN() string {
	if m != nil {
		return m.LastN
	}
	return ""
}

func (m *Person_Name) GetGivenN() string {
	if m != nil {
		return m.GivenN
	}
	return ""
}

type Person_Email struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person_Email) Reset()         { *m = Person_Email{} }
func (m *Person_Email) String() string { return proto.CompactTextString(m) }
func (*Person_Email) ProtoMessage()    {}
func (*Person_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 1}
}

func (m *Person_Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_Email.Unmarshal(m, b)
}
func (m *Person_Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_Email.Marshal(b, m, deterministic)
}
func (m *Person_Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_Email.Merge(m, src)
}
func (m *Person_Email) XXX_Size() int {
	return xxx_messageInfo_Person_Email.Size(m)
}
func (m *Person_Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Person_Email proto.InternalMessageInfo

func (m *Person_Email) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Person_Email) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "person.Person")
	proto.RegisterType((*Person_Name)(nil), "person.Person.Name")
	proto.RegisterType((*Person_Email)(nil), "person.Person.Email")
}

func init() {
	proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d)
}

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x0e, 0x30, 0x72,
	0xb1, 0x05, 0x80, 0x99, 0x42, 0xea, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x50, 0xf5, 0x10, 0x59, 0x3d, 0xbf, 0xc4, 0xdc, 0xd4, 0x20, 0xb0,
	0x02, 0x21, 0x2d, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x11, 0x34, 0x95, 0xae, 0x20, 0xb9, 0x20, 0x88, 0x12, 0x29, 0x13, 0x2e, 0x16, 0x90, 0x4e,
	0x21, 0x11, 0x2e, 0xd6, 0x9c, 0xc4, 0xe2, 0x12, 0x3f, 0xb0, 0xe9, 0x9c, 0x41, 0x10, 0x8e, 0x90,
	0x18, 0x17, 0x5b, 0x7a, 0x66, 0x59, 0x6a, 0x9e, 0x9f, 0x04, 0x13, 0x58, 0x18, 0xca, 0x93, 0xd2,
	0xe6, 0x62, 0x05, 0x9b, 0x22, 0x24, 0xc4, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x0a, 0xd5, 0x05, 0x66,
	0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x40, 0x35, 0x30, 0x65, 0xa6, 0x24, 0xb1, 0x81, 0x7d, 0x64,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x37, 0x75, 0x89, 0xe1, 0x00, 0x00, 0x00,
}
